name: contacts
description: List of important contacts.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: 2.0.1
  cupertino_icons: ^1.0.2
  go_router: ^6.5.7
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/contacts/
